---
- hosts: worker1
  become: yes 
  tasks: 
    - name: Login to the Nexus Regisry 
      docker_login:
        registry_url: https://registry.anuznomii.lol
        username: "admin"
        password: "nexus@2023"
    - name: Push Docker image to Nexus registry
      community.docker.docker_image:
        name: registry.anuznomii.lol/web14-reactjs
        push: yes
       