---
- hosts: worker1
  become: yes 
  tasks: 
    - name: Login to the Nexus Regisry 
      docker_login:
        registry_url: https://registry.anuznomii.lol
        username: "admin"
        password: "nexus@2023"
    - name: Push Image to Nexus Repo 
      docker_image:
          name: "registry.anuznomii.lol/web14-reactjs"
          repository: "https://registry.anuznomii.lol"
          tag: "latest"
          push: yes
          state: present
