- name: Execute the shellscript
  hosts: workers
  tasks:
    - name: Create a directory
      file:
        path: /home/ubuntu/shellscript
        state: directory
        mode: 0777

    - name: Copy the shellscript to the remote server
      copy:
        src: ./shellscript/testing.sh
        dest: /home/ubuntu/shellscript/
        mode: 0777

    - name: Execute the shellscript 
      shell: /bin/bash ./home/ubuntu/shellscript/testing.sh  
      args:
        creates: /home/ubuntu/shellscript/testing.sh
